// MSW Request Handlers for API Mocking
import { rest } from 'msw';

// Base URL for API endpoints
const API_BASE = 'http://localhost:3000/api';

// AI Provider responses
const mockAIResponses = {
  mathematics: {
    'what-is-pythagoras': {
      answer: 'The Pythagorean theorem states that in a right triangle, the square of the length of the hypotenuse equals the sum of squares of the other two sides (a² + b² = c²).',
      confidence: 0.95,
      followUpQuestions: [
        'Can you show me an example with specific numbers?',
        'How is this used in real life applications?',
        'What about triangles that aren\'t right triangles?'
      ],
      subject: 'mathematics',
      level: 'high-school'
    }
  },
  physics: {
    'newton-laws': {
      answer: 'Newton\'s three laws of motion are: 1) An object at rest stays at rest, and an object in motion stays in motion unless acted upon by an external force. 2) F = ma (Force equals mass times acceleration). 3) For every action, there is an equal and opposite reaction.',
      confidence: 0.92,
      followUpQuestions: [
        'Can you give real-world examples of each law?',
        'How do these laws apply in space?',
        'What are the limitations of Newton\'s laws?'
      ],
      subject: 'physics',
      level: 'high-school'
    }
  },
  programming: {
    'react-hooks': {
      answer: 'React Hooks are functions that let you use state and other React features in functional components. Common hooks include useState for state management, useEffect for side effects, and useContext for accessing context values.',
      confidence: 0.88,
      followUpQuestions: [
        'How do custom hooks work?',
        'What are the rules of hooks?',
        'Can you show me a practical example?'
      ],
      subject: 'programming',
      level: 'intermediate'
    }
  }
};

// Generate dynamic AI responses based on question content
const generateAIResponse = (question, subject, level) => {
  const questionKey = question.toLowerCase().replace(/[^a-z0-9]/g, '-');

  // Check for predefined responses
  if (mockAIResponses[subject] && mockAIResponses[subject][questionKey]) {
    return mockAIResponses[subject][questionKey];
  }

  // Generate generic response
  return {
    answer: `This is a comprehensive answer about "${question}" in ${subject} at ${level} level. The response would normally be generated by the AI provider (Gemini, OpenRouter, or Z.AI) based on the specific question parameters.`,
    confidence: 0.85,
    followUpQuestions: [
      'Would you like me to explain this in more detail?',
      'Can I provide you with some examples?',
      'Do you have any follow-up questions on this topic?'
    ],
    subject,
    level
  };
};

// API Handlers
export const handlers = [
  // POST /api/ask - AI Question Answering
  rest.post(`${API_BASE}/ask`, (req, res, ctx) => {
    const { question, subject = 'general', level = 'adaptive' } = req.body;

    // Validate required fields
    if (!question || typeof question !== 'string') {
      return res(
        ctx.status(400),
        ctx.json({
          error: 'Question is required and must be a string'
        })
      );
    }

    // Simulate processing delay
    const processingTime = Math.random() * 1000 + 500; // 500-1500ms

    setTimeout(() => {
      // Generate response based on question
      const response = generateAIResponse(question, subject, level);

      return res(
        ctx.status(200),
        ctx.json(response)
      );
    }, processingTime);
  }),

  // GET /api/subjects - Available Subjects
  rest.get(`${API_BASE}/subjects`, (req, res, ctx) => {
    return res(
      ctx.status(200),
      ctx.json({
        subjects: [
          { id: 'mathematics', name: 'Mathematics', icon: '📐' },
          { id: 'physics', name: 'Physics', icon: '⚛️' },
          { id: 'chemistry', name: 'Chemistry', icon: '🧪' },
          { id: 'biology', name: 'Biology', icon: '🧬' },
          { id: 'programming', name: 'Programming', icon: '💻' },
          { id: 'language', name: 'Language Arts', icon: '📖' },
          { id: 'history', name: 'History', icon: '📚' },
          { id: 'general', name: 'General Knowledge', icon: '🎯' }
        ]
      })
    );
  }),

  // POST /api/generate/quiz - Quiz Generation
  rest.post(`${API_BASE}/generate/quiz`, (req, res, ctx) => {
    const { subject, topics = [], questionCount = 5, difficulty = 'medium' } = req.body;

    // Validate request
    if (!subject) {
      return res(
        ctx.status(400),
        ctx.json({ error: 'Subject is required' })
      );
    }

    const mockQuiz = {
      id: `quiz-${Date.now()}`,
      title: `${subject} Quiz`,
      subject,
      difficulty,
      questions: Array.from({ length: questionCount }, (_, i) => ({
        id: `q${i + 1}`,
        question: `Sample question ${i + 1} about ${topics.length > 0 ? topics[0] : subject}`,
        type: 'multiple-choice',
        options: [
          'Option A: Correct answer',
          'Option B: Incorrect option',
          'Option C: Another incorrect option',
          'Option D: Final incorrect option'
        ],
        correctAnswer: 0,
        explanation: `Explanation for why the correct answer is right and others are wrong.`
      })),
      timeLimit: questionCount * 60, // 1 minute per question
      passingScore: 70
    };

    return res(
      ctx.status(200),
      ctx.json(mockQuiz)
    );
  }),

  // POST /api/generate/flashcards - Flashcard Generation
  rest.post(`${API_BASE}/generate/flashcards`, (req, res, ctx) => {
    const { topic, count = 10, difficulty = 'medium' } = req.body;

    if (!topic) {
      return res(
        ctx.status(400),
        ctx.json({ error: 'Topic is required' })
      );
    }

    const mockFlashcards = Array.from({ length: count }, (_, i) => ({
      id: `card-${Date.now()}-${i}`,
      front: `What is ${topic} concept ${i + 1}?`,
      back: `Detailed explanation of ${topic} concept ${i + 1} with key points and examples.`,
      difficulty,
      category: topic,
      tags: [topic, 'concept', `level-${difficulty}`]
    }));

    return res(
      ctx.status(200),
      ctx.json({
        flashcards: mockFlashcards,
        topic,
        totalCards: count
      })
    );
  }),

  // GET /api/user/progress/:userId - User Progress
  rest.get(`${API_BASE}/user/progress/:userId`, (req, res, ctx) => {
    const { userId } = req.params;

    if (!userId) {
      return res(
        ctx.status(400),
        ctx.json({ error: 'User ID is required' })
      );
    }

    const mockProgress = {
      userId,
      overallProgress: 75,
      subjects: [
        {
          subject: 'mathematics',
          progress: 85,
          questionsAnswered: 42,
          correctAnswers: 36,
          timeSpent: 180, // minutes
          lastActivity: new Date().toISOString()
        },
        {
          subject: 'physics',
          progress: 60,
          questionsAnswered: 25,
          correctAnswers: 15,
          timeSpent: 120,
          lastActivity: new Date(Date.now() - 86400000).toISOString() // 1 day ago
        }
      ],
      achievements: [
        { id: 'first-question', name: 'First Question', earnedAt: new Date().toISOString() },
        { id: 'week-streak', name: 'Week Streak', earnedAt: new Date(Date.now() - 604800000).toISOString() }
      ],
      learningStreak: 5,
      totalStudyTime: 300 // minutes
    };

    return res(
      ctx.status(200),
      ctx.json(mockProgress)
    );
  }),

  // POST /api/user/progress/:userId - Update User Progress
  rest.post(`${API_BASE}/user/progress/:userId`, (req, res, ctx) => {
    const { userId } = req.params;
    const { subject, questionAnswered, correct, timeSpent } = req.body;

    if (!userId || !subject) {
      return res(
        ctx.status(400),
        ctx.json({ error: 'User ID and subject are required' })
      );
    }

    return res(
      ctx.status(200),
      ctx.json({
        success: true,
        message: 'Progress updated successfully',
        updatedProgress: {
          userId,
          subject,
          questionsAnswered: questionAnswered + 1,
          correctAnswers: correct ? 1 : 0,
          timeSpent: timeSpent || 1
        }
      })
    );
  }),

  // Error handling handlers
  rest.get(`${API_BASE}/error-test`, (req, res, ctx) => {
    return res(
      ctx.status(500),
      ctx.json({ error: 'Internal server error' })
    );
  }),

  // Rate limiting simulation
  rest.post(`${API_BASE}/rate-limited`, (req, res, ctx) => {
    return res(
      ctx.status(429),
      ctx.json({
        error: 'Rate limit exceeded',
        retryAfter: 60
      })
    );
  }),

  // AI Provider error simulation
  rest.post(`${API_BASE}/ai-error`, (req, res, ctx) => {
    return res(
      ctx.status(503),
      ctx.json({
        error: 'AI service temporarily unavailable',
        message: 'Please try again in a few moments'
      })
    );
  })
];